import type { ChoirEvent, Fundraiser, GalleryItem, TicketTier } from "../types";

const choirImg = "/images/choir-main.jpg";

export const seedTiers: Record<string, TicketTier[]> = {
  "hes-risen-2026": [
    {
      id: "tier-regular",
      event_id: "hes-risen-2026",
      name: "Regular",
      description: "General seating",
      price_kes: 500,
      capacity: 400,
      perks: ["General seating", "Digital ticket"],
      sort_order: 1,
      active: true,
    },
    {
      id: "tier-vip",
      event_id: "hes-risen-2026",
      name: "VIP",
      description: "Reserved + meet & greet",
      price_kes: 1500,
      capacity: 80,
      perks: ["Reserved seating", "Meet & greet", "Program booklet"],
      sort_order: 2,
      active: true,
    },
    {
      id: "tier-family",
      event_id: "hes-risen-2026",
      name: "Family (4)",
      description: "Four regular seats",
      price_kes: 1600,
      capacity: 50,
      perks: ["Four regular seats", "Shared booking"],
      sort_order: 3,
      active: true,
    },
  ],
  "night-of-praise-2026": [
    {
      id: "tier-gate",
      event_id: "night-of-praise-2026",
      name: "Gate",
      description: "Lawn / standing",
      price_kes: 300,
      capacity: null,
      perks: ["Standing / lawn"],
      sort_order: 1,
      active: true,
    },
    {
      id: "tier-reserved",
      event_id: "night-of-praise-2026",
      name: "Reserved",
      description: "Chair seating",
      price_kes: 800,
      capacity: 200,
      perks: ["Chair seating", "Priority entry"],
      sort_order: 2,
      active: true,
    },
  ],
  "community-worship-free": [
    {
      id: "tier-free",
      event_id: "community-worship-free",
      name: "Free admission",
      description: "Register your seat",
      price_kes: 0,
      capacity: 500,
      perks: ["Free entry", "Confirmation email"],
      sort_order: 1,
      active: true,
    },
  ],
};

export const seedEvents: ChoirEvent[] = [
  {
    id: "hes-risen-2026",
    slug: "hes-risen-2026",
    title: "He's Risen Concert",
    tagline: "An Easter celebration of hope in song",
    description:
      "Join Echoes of Praise for an evening of gospel excellence—choral classics, contemporary worship, and the joy of the risen Christ.",
    starts_at: "2026-04-05T16:00:00+03:00",
    ends_at: "2026-04-05T19:00:00+03:00",
    venue: "Nakuru Players Theatre",
    city: "Nakuru",
    county: "Nakuru",
    location_notes: "",
    cover_image_url: choirImg,
    status: "published",
    is_free: false,
    featured: true,
    external_ticket_url: null,
    ticket_tiers: seedTiers["hes-risen-2026"],
  },
  {
    id: "night-of-praise-2026",
    slug: "night-of-praise-2026",
    title: "Night of Praise",
    tagline: "Worship under Nakuru skies",
    description:
      "An open-air night of praise featuring Echoes of Praise and guest worship leaders from across the Rift Valley.",
    starts_at: "2026-08-15T18:30:00+03:00",
    ends_at: "2026-08-15T21:30:00+03:00",
    venue: "Christ the King Cathedral Grounds",
    city: "Nakuru",
    county: "Nakuru",
    location_notes: "",
    cover_image_url: "/images/gallery/eop-16.jpg",
    status: "published",
    is_free: false,
    featured: false,
    external_ticket_url: null,
    ticket_tiers: seedTiers["night-of-praise-2026"],
  },
  {
    id: "community-worship-free",
    slug: "community-worship-free",
    title: "Community Worship Night",
    tagline: "Free night of praise for Nakuru families",
    description:
      "A free community worship evening. Register for free tickets so we can prepare seating and hospitality.",
    starts_at: "2026-09-20T17:00:00+03:00",
    ends_at: "2026-09-20T19:30:00+03:00",
    venue: "Community Hall, Section 58",
    city: "Nakuru",
    county: "Nakuru",
    location_notes: "",
    cover_image_url: "/images/gallery/eop-05.jpg",
    status: "published",
    is_free: true,
    featured: false,
    external_ticket_url: null,
    ticket_tiers: seedTiers["community-worship-free"],
  },
  {
    id: "christmas-carol-2025",
    slug: "christmas-carol-2025",
    title: "Christmas Carol Service",
    tagline: "Lessons and carols with Echoes of Praise",
    description: "A beloved evening of carols, readings, and choral praise.",
    starts_at: "2025-12-14T16:00:00+03:00",
    ends_at: "2025-12-14T18:30:00+03:00",
    venue: "Town Church",
    city: "Nakuru",
    county: "Nakuru",
    location_notes: "",
    cover_image_url: "/images/gallery/eop-01.jpg",
    status: "published",
    is_free: true,
    featured: false,
    external_ticket_url: null,
    ticket_tiers: [],
  },
];

export const seedFundraisers: Fundraiser[] = [
  {
    id: "support-the-choir",
    slug: "support-the-choir",
    title: "Support the Choir",
    subtitle: "Ongoing giving for ministry, rehearsals, and outreach",
    story:
      "Your gifts help Echoes of Praise travel, rehearse, costume, and minister across Nakuru and beyond. This fund is always open.",
    kind: "ongoing_support",
    goal_kes: null,
    raised_kes: 0,
    show_progress: false,
    cover_image_url: choirImg,
    active: true,
    event_id: null,
    starts_at: null,
    ends_at: null,
  },
  {
    id: "lift-the-sound",
    slug: "lift-the-sound",
    title: "Lift the Sound",
    subtitle: "Professional sound system for Echoes of Praise",
    story:
      "Help us purchase a full professional sound system—mixer, mics, mains, and monitors—so every concert is heard clearly.",
    kind: "campaign",
    goal_kes: 850000,
    raised_kes: 312500,
    show_progress: true,
    cover_image_url: "/images/gallery/eop-13.jpg",
    active: true,
    event_id: null,
    starts_at: null,
    ends_at: null,
  },
];

const galleryMeta: Array<{ title: string; caption: string; category: string }> = [
  { title: "In rehearsal", caption: "Preparing the blend.", category: "rehearsals" },
  { title: "On stage together", caption: "Echoes of Praise — full choir.", category: "concerts" },
  { title: "Worship moment", caption: "Voices lifted in praise.", category: "concerts" },
  { title: "Ministry in song", caption: "Serving from Nakuru.", category: "outreach" },
  { title: "Choir family", caption: "Generations singing as one.", category: "concerts" },
  { title: "Front row joy", caption: "Young voices in the ministry.", category: "concerts" },
  { title: "Harmony", caption: "Green and white — our colours.", category: "concerts" },
  { title: "Afterglow", caption: "A night of praise remembered.", category: "concerts" },
  { title: "Stage light", caption: "Ready for the next song.", category: "concerts" },
  { title: "Fellowship", caption: "Side by side in worship.", category: "outreach" },
  { title: "Focus", caption: "Eyes on the Director.", category: "rehearsals" },
  { title: "Presence", caption: "Holding the room in song.", category: "concerts" },
  { title: "Sound check", caption: "Building toward Lift the Sound.", category: "rehearsals" },
  { title: "Together", caption: "The choir that carries Nakuru’s praise.", category: "concerts" },
  { title: "Celebration", caption: "Joy in every part.", category: "concerts" },
  { title: "Encore spirit", caption: "One more song for His glory.", category: "concerts" },
];

export const seedGallery: GalleryItem[] = galleryMeta.map((meta, i) => {
  const n = String(i + 1).padStart(2, "0");
  return {
    id: `gal-${n}`,
    title: meta.title,
    caption: meta.caption,
    image_url: `/images/gallery/eop-${n}.jpg`,
    category: meta.category,
    published: true,
    sort_order: i + 1,
    taken_at: "2025-11-28",
  };
});
