import { choirMembers as staticChoirMembers } from "../content/choir";
import type {
  ChoirEvent,
  Fundraiser,
  GalleryAlbum,
  GalleryItem,
  RosterMember,
  TicketTier,
} from "../types";

const choirImg = "/images/choir-main.jpg";
const oneCover = "/images/events/one-concert-cenacle.png";
const choristersCover = "/images/events/choristers-sabbath-2026.png";

export const seedTiers: Record<string, TicketTier[]> = {
  "hes-risen-2026": [
    {
      id: "tier-regular",
      event_id: "hes-risen-2026",
      name: "Regular",
      description: "General seating",
      price_kes: 500,
      capacity: 400,
      perks: ["General seating", "Digital ticket"],
      sort_order: 1,
      active: true,
    },
    {
      id: "tier-vip",
      event_id: "hes-risen-2026",
      name: "VIP",
      description: "Reserved + meet & greet",
      price_kes: 1500,
      capacity: 80,
      perks: ["Reserved seating", "Meet & greet", "Program booklet"],
      sort_order: 2,
      active: true,
    },
    {
      id: "tier-family",
      event_id: "hes-risen-2026",
      name: "Family (4)",
      description: "Four regular seats",
      price_kes: 1600,
      capacity: 50,
      perks: ["Four regular seats", "Shared booking"],
      sort_order: 3,
      active: true,
    },
  ],
  "night-of-praise-2026": [
    {
      id: "tier-gate",
      event_id: "night-of-praise-2026",
      name: "Gate",
      description: "Lawn / standing",
      price_kes: 300,
      capacity: null,
      perks: ["Standing / lawn"],
      sort_order: 1,
      active: true,
    },
    {
      id: "tier-reserved",
      event_id: "night-of-praise-2026",
      name: "Reserved",
      description: "Chair seating",
      price_kes: 800,
      capacity: 200,
      perks: ["Chair seating", "Priority entry"],
      sort_order: 2,
      active: true,
    },
  ],
  "community-worship-free": [
    {
      id: "tier-free",
      event_id: "community-worship-free",
      name: "Free admission",
      description: "Register your seat",
      price_kes: 0,
      capacity: 500,
      perks: ["Free entry", "Confirmation email"],
      sort_order: 1,
      active: true,
    },
  ],
  "one-concert-2026": [],
};

export const seedEvents: ChoirEvent[] = [
  {
    id: "one-concert-2026",
    slug: "one-concert-2026",
    title: "Echoes of Praise ONE Concert",
    tagline: "1-year anniversary · Theme: Praise Amplified",
    description:
      "Celebrate one year of Echoes of Praise with our anniversary concert—Praise Amplified. Featuring guest choir The Cenacle Ministry (Uganda) and Merge Acapella (Kenya), live at Crater SDA Church, Nakuru. Ticketing information coming soon; you can support the concert through the anniversary fundraiser.",
    starts_at: "2026-11-29T14:00:00+03:00",
    ends_at: "2026-11-29T18:00:00+03:00",
    venue: "Crater SDA Church",
    city: "Nakuru",
    county: "Nakuru",
    location_notes:
      "Guests: The Cenacle Ministry (Uganda) · Merge Acapella (Kenya)",
    cover_image_url: oneCover,
    status: "published",
    is_free: false,
    featured: true,
    external_ticket_url: null,
    ticket_tiers: seedTiers["one-concert-2026"],
  },
  {
    id: "choristers-sabbath-2026",
    slug: "choristers-sabbath-2026",
    title: "Choristers' Sabbath",
    tagline: "The Password of Thanksgiving · Sunshine SDA Church",
    description:
      "Echoes of Praise ministered at Choristers' Sabbath at Sunshine SDA Church—The Password of Thanksgiving—a full Sabbath of worship and choral praise from 8 AM to 6 PM.",
    starts_at: "2026-05-09T08:00:00+03:00",
    ends_at: "2026-05-09T18:00:00+03:00",
    venue: "Sunshine SDA Church",
    city: "Nakuru",
    county: "Nakuru",
    location_notes: "Featuring The Echoes of Praise Choir",
    cover_image_url: choristersCover,
    status: "published",
    is_free: true,
    featured: false,
    external_ticket_url: null,
    ticket_tiers: [],
  },
  {
    id: "hes-risen-2026",
    slug: "hes-risen-2026",
    title: "He's Risen Concert",
    tagline: "An Easter celebration of hope in song",
    description:
      "Join Echoes of Praise for an evening of gospel excellence—choral classics, contemporary worship, and the joy of the risen Christ.",
    starts_at: "2026-04-05T16:00:00+03:00",
    ends_at: "2026-04-05T19:00:00+03:00",
    venue: "Nakuru Players Theatre",
    city: "Nakuru",
    county: "Nakuru",
    location_notes: "",
    cover_image_url: choirImg,
    status: "published",
    is_free: false,
    featured: false,
    external_ticket_url: null,
    ticket_tiers: seedTiers["hes-risen-2026"],
  },
  {
    id: "night-of-praise-2026",
    slug: "night-of-praise-2026",
    title: "Night of Praise",
    tagline: "Worship under Nakuru skies",
    description:
      "An open-air night of praise featuring Echoes of Praise and guest worship leaders from across the Rift Valley.",
    starts_at: "2026-08-15T18:30:00+03:00",
    ends_at: "2026-08-15T21:30:00+03:00",
    venue: "Christ the King Cathedral Grounds",
    city: "Nakuru",
    county: "Nakuru",
    location_notes: "",
    cover_image_url: choirImg,
    status: "published",
    is_free: false,
    featured: false,
    external_ticket_url: null,
    ticket_tiers: seedTiers["night-of-praise-2026"],
  },
  {
    id: "community-worship-free",
    slug: "community-worship-free",
    title: "Community Worship Night",
    tagline: "Free night of praise for Nakuru families",
    description:
      "A free community worship evening. Register for free tickets so we can prepare seating and hospitality.",
    starts_at: "2026-09-20T17:00:00+03:00",
    ends_at: "2026-09-20T19:30:00+03:00",
    venue: "Community Hall, Section 58",
    city: "Nakuru",
    county: "Nakuru",
    location_notes: "",
    cover_image_url: choirImg,
    status: "published",
    is_free: true,
    featured: false,
    external_ticket_url: null,
    ticket_tiers: seedTiers["community-worship-free"],
  },
  {
    id: "christmas-carol-2025",
    slug: "christmas-carol-2025",
    title: "Christmas Carol Service",
    tagline: "Lessons and carols with Echoes of Praise",
    description: "A beloved evening of carols, readings, and choral praise.",
    starts_at: "2025-12-14T16:00:00+03:00",
    ends_at: "2025-12-14T18:30:00+03:00",
    venue: "Town Church",
    city: "Nakuru",
    county: "Nakuru",
    location_notes: "",
    cover_image_url: choirImg,
    status: "published",
    is_free: true,
    featured: false,
    external_ticket_url: null,
    ticket_tiers: [],
  },
];

export const seedFundraisers: Fundraiser[] = [
  {
    id: "one-concert-2026",
    slug: "one-concert-2026",
    title: "ONE Concert Anniversary Fund",
    subtitle: "Help us host Praise Amplified — 29 November 2026",
    story:
      "Support Echoes of Praise as we mark one year of ministry with our ONE Concert at Crater SDA Church, Nakuru. Gifts help cover guest hospitality for The Cenacle Ministry (Uganda) and Merge Acapella (Kenya), staging, sound, and production for Praise Amplified. Tickets are not yet on sale—your giving now builds the night.",
    kind: "campaign",
    goal_kes: 500000,
    raised_kes: 0,
    show_progress: true,
    cover_image_url: oneCover,
    active: true,
    archived_at: null,
    event_id: "one-concert-2026",
    starts_at: "2026-07-01T00:00:00+03:00",
    ends_at: "2026-11-29T23:59:00+03:00",
  },
  {
    id: "support-the-choir",
    slug: "support-the-choir",
    title: "Support the Choir",
    subtitle: "Ongoing giving for ministry, rehearsals, and outreach",
    story:
      "Your gifts help Echoes of Praise travel, rehearse, costume, and minister across Nakuru and beyond. This fund is always open.",
    kind: "ongoing_support",
    goal_kes: null,
    raised_kes: 0,
    show_progress: false,
    cover_image_url: choirImg,
    active: true,
    archived_at: null,
    event_id: null,
    starts_at: null,
    ends_at: null,
  },
  {
    id: "lift-the-sound",
    slug: "lift-the-sound",
    title: "Lift the Sound",
    subtitle: "Professional sound system for Echoes of Praise",
    story:
      "Help us purchase a full professional sound system—mixer, mics, mains, and monitors—so every concert is heard clearly.",
    kind: "campaign",
    goal_kes: 850000,
    raised_kes: 312500,
    show_progress: true,
    cover_image_url: "/images/gallery/eop-13.jpg",
    active: true,
    archived_at: null,
    event_id: null,
    starts_at: null,
    ends_at: null,
  },
];

const galleryMeta: Array<{ title: string; caption: string; category: string }> = [
  { title: "In rehearsal", caption: "Preparing the blend.", category: "rehearsals" },
  { title: "On stage together", caption: "Echoes of Praise — full choir.", category: "concerts" },
  { title: "Worship moment", caption: "Voices lifted in praise.", category: "concerts" },
  { title: "Ministry in song", caption: "Serving from Nakuru.", category: "outreach" },
  { title: "Choir family", caption: "Generations singing as one.", category: "concerts" },
  { title: "Front row joy", caption: "Young voices in the ministry.", category: "concerts" },
  { title: "Harmony", caption: "Green and white — our colours.", category: "concerts" },
  { title: "Afterglow", caption: "A night of praise remembered.", category: "concerts" },
  { title: "Stage light", caption: "Ready for the next song.", category: "concerts" },
  { title: "Fellowship", caption: "Side by side in worship.", category: "outreach" },
  { title: "Focus", caption: "Eyes on the Director.", category: "rehearsals" },
  { title: "Presence", caption: "Holding the room in song.", category: "concerts" },
  { title: "Sound check", caption: "Building toward Lift the Sound.", category: "rehearsals" },
  { title: "Together", caption: "The choir that carries Nakuru’s praise.", category: "concerts" },
  { title: "Celebration", caption: "Joy in every part.", category: "concerts" },
  { title: "Encore spirit", caption: "One more song for His glory.", category: "concerts" },
];

export const seedGalleryAlbums: GalleryAlbum[] = [
  {
    id: "album-ministry-moments",
    slug: "ministry-moments",
    title: "Ministry moments",
    description:
      "Highlights from rehearsals, concerts, and outreach with Echoes of Praise.",
    event_date: "2025-11-28",
    cover_image_url: "/images/gallery/eop-02.jpg",
    cover_focus_x: 50,
    cover_focus_y: 35,
    published: true,
    sort_order: 1,
  },
];

export const seedGallery: GalleryItem[] = galleryMeta.map((meta, i) => {
  const n = String(i + 1).padStart(2, "0");
  return {
    id: `gal-${n}`,
    title: meta.title,
    caption: meta.caption,
    image_url: `/images/gallery/eop-${n}.jpg`,
    category: meta.category,
    published: true,
    sort_order: i + 1,
    taken_at: "2025-11-28",
    album_id: "album-ministry-moments",
  };
});

export const seedChoirMembers: RosterMember[] = staticChoirMembers.map(
  (m, i) => ({
    id: m.id,
    name: m.name,
    section: m.section ?? null,
    sort_order: i + 1,
    published: true,
  }),
);
